name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-corss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            output: redirect
          - target: x86_64-unknown-linux-musl
            output: redirect
          - target: x86_64-pc-windows-gnu
            output: redirect.exe
    steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: pack
        run: |
          mkdir -p release-${{ matrix.target }}
          cd release-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release -zcf redirect-${{ matrix.target }}.tar.gz ${{ matrix.output }}
          sha256sum redirect-${{ matrix.target }}.tar.gz > redirect-${{ matrix.target }}.sha256
      - name: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release-${{ matrix.target }}/*
  release-apple:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --release --target=${{ matrix.target }}
      - name: pack
        run: |
          mkdir -p release-${{ matrix.target }}
          cd release-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release/ -zcf redirect-${{ matrix.target }}.tar.gz redirect
          shasum -a 256 redirect-${{ matrix.target }}.tar.gz > redirect-${{ matrix.target }}.sha256
      - name: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release-${{ matrix.target }}/*
